variables:
  Solution: runner.sln 
before_script:

stages:
  - build
  - test
  - deploy

build:
  stage: build
  script:
  - echo building...
test:
  stage: test
  script:
  - echo This is testing phase
deployment:
  stage: deploy
  script: 
  - echo deplying..